name: Build

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
  build:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - name: Build
        run: zig build
      - name: Deploy
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: zig-out
      - name: Upload release
        id: upload-release-linux
        uses: alexellis/upload-assets@0.2.3
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_paths: '["./zig-out/bin/crash.arm-linux-musleabihf", "./zig-out/bin/crash.x86_64-linux-musl"]'
