name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
      - name: Build
        run: zig build
      - name: Deploy
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: zig-out
